version: "3.7"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /path/to/redis-persistence:/bitnami/redis/data

  worker:
    build: .
    command: celery -A src worker -l info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A src beat -l info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - worker
  bot:
    build: .
    command: python bot.py
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - beat